services:
        db:
          image: postgres:17
          restart: always
          environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
          ports:
            - "5432:5432"
          volumes:
            - railDB:/var/lib/postgresql/data
volumes:
        railDB:
