services:
  db:
    image: postgres:17
    restart: always
    environment:
        POSTGRES_USER: debojit
        POSTGRES_PASSWORD: password
        POSTGRES_DB: railwayDatabase
    ports:
      - "5432:5432"
    volumes:
      - railDB:/var/lib/postgresql/data
volumes:
  railDB:
